using Microsoft.CodeAnalysis;

namespace Moongazing.OrionKey.Generators;

/// <summary>
/// Incremental generator that turns <c>[OrionId]</c>-decorated structs into fully-featured
/// strongly-typed ids.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class OrionIdGenerator : IIncrementalGenerator
{
    private const string OneArgAttribute = "Moongazing.OrionKey.OrionIdAttribute`1";
    private const string TwoArgAttribute = "Moongazing.OrionKey.OrionIdAttribute`2";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var oneArg = context.SyntaxProvider.ForAttributeWithMetadataName(
            OneArgAttribute,
            predicate: static (node, _) => true,
            transform: static (ctx, _) => ctx.TargetSymbol as INamedTypeSymbol);

        var twoArg = context.SyntaxProvider.ForAttributeWithMetadataName(
            TwoArgAttribute,
            predicate: static (node, _) => true,
            transform: static (ctx, _) => ctx.TargetSymbol as INamedTypeSymbol);

        context.RegisterSourceOutput(oneArg, static (spc, symbol) => EmitSkeleton(spc, symbol));
        context.RegisterSourceOutput(twoArg, static (spc, symbol) => EmitSkeleton(spc, symbol));
    }

    private static void EmitSkeleton(SourceProductionContext spc, INamedTypeSymbol? symbol)
    {
        if (symbol is null)
        {
            return;
        }
        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : symbol.ContainingNamespace.ToDisplayString();
        var nsBlock = ns.Length == 0 ? string.Empty : $"namespace {ns};\n\n";
        spc.AddSource(
            $"{symbol.Name}.OrionId.g.cs",
            $"// <auto-generated/>\n{nsBlock}readonly partial struct {symbol.Name} {{ }}\n");
    }
}
