using System.Text;
using Moongazing.OrionKey.Generators.Model;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>
/// Emits IComparable + ordering operators for EVERY id type. v0.5.26: previously only
/// sortable (time-ordered) strategies got IComparable; now ALL ids are comparable.
/// Sortable strategies keep their creation-ordered comparison; all other ids get a
/// deterministic value-based comparison (stable across processes, NOT chronological)
/// so they can be used as SortedSet / SortedDictionary keys, OrderBy / binary-search
/// targets, and produce stable test output.
/// </summary>
internal static class ComparableEmitter
{
    /// <summary>Returns the comparable partial for any id model (never null since v0.5.26).</summary>
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"readonly partial struct {name} : "
                    + $"global::System.IComparable<{name}>, global::System.IComparable");
        sb.AppendLine("{");
        sb.AppendLine($"    public int CompareTo({name} other) => {CompareExpression(model)};");
        sb.AppendLine("    public int CompareTo(object? obj) => obj switch");
        sb.AppendLine("    {");
        sb.AppendLine("        null => 1,");
        sb.AppendLine($"        {name} other => CompareTo(other),");
        sb.AppendLine("        _ => throw new global::System.ArgumentException("
                    + $"\"Object must be of type {name}.\", nameof(obj)),");
        sb.AppendLine("    };");
        sb.AppendLine($"    public static bool operator <({name} left, {name} right) => left.CompareTo(right) < 0;");
        sb.AppendLine($"    public static bool operator <=({name} left, {name} right) => left.CompareTo(right) <= 0;");
        sb.AppendLine($"    public static bool operator >({name} left, {name} right) => left.CompareTo(right) > 0;");
        sb.AppendLine($"    public static bool operator >=({name} left, {name} right) => left.CompareTo(right) >= 0;");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string CompareExpression(OrionIdModel model) => model.Strategy switch
    {
        // Time-ordered strategies: creation-ordered comparison (v0.3.x behaviour).
        StrategyType.GuidV7 =>
            "global::Moongazing.OrionKey.OrionGuidComparer.CompareV7(Value, other.Value)",
        StrategyType.SequentialGuid =>
            "global::Moongazing.OrionKey.OrionGuidComparer.CompareSequential(Value, other.Value)",
        StrategyType.Ulid or StrategyType.Ksuid or StrategyType.ObjectId or StrategyType.MonotonicHex =>
            "global::System.String.CompareOrdinal(Value, other.Value)",
        StrategyType.Snowflake => "Value.CompareTo(other.Value)",
        // v0.5.26: all other ids fall back to a deterministic value-based comparison.
        // Not chronological (the underlying value carries no time component) but stable
        // and total - sufficient for SortedSet keys, OrderBy, and deterministic output.
        _ => ValueComparison(model.ValueType),
    };

    private static string ValueComparison(Model.ValueType valueType) => valueType switch
    {
        // String.CompareOrdinal is null-safe and culture-independent.
        Model.ValueType.String => "global::System.String.CompareOrdinal(Value, other.Value)",
        // Guid/int/long all expose a deterministic IComparable<T>.CompareTo.
        _ => "Value.CompareTo(other.Value)",
    };
}
