using System.Text;
using Moongazing.OrionKey.Generators.Model;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits IComparable + ordering operators for sortable id strategies.</summary>
internal static class ComparableEmitter
{
    /// <summary>Returns the comparable partial, or null when the model is not sortable.</summary>
    public static string? Emit(OrionIdModel model)
    {
        if (!model.IsSortable)
        {
            return null;
        }

        var name = model.Name;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"readonly partial struct {name} : "
                    + $"global::System.IComparable<{name}>, global::System.IComparable");
        sb.AppendLine("{");
        sb.AppendLine($"    public int CompareTo({name} other) => "
                    + "global::System.Collections.Generic.Comparer<"
                    + $"{model.ValueKeyword}>.Default.Compare(Value, other.Value);");
        sb.AppendLine("    public int CompareTo(object? obj) => obj switch");
        sb.AppendLine("    {");
        sb.AppendLine("        null => 1,");
        sb.AppendLine($"        {name} other => CompareTo(other),");
        sb.AppendLine("        _ => throw new global::System.ArgumentException("
                    + $"\"Object must be of type {name}.\", nameof(obj)),");
        sb.AppendLine("    };");
        sb.AppendLine($"    public static bool operator <({name} left, {name} right) => left.CompareTo(right) < 0;");
        sb.AppendLine($"    public static bool operator <=({name} left, {name} right) => left.CompareTo(right) <= 0;");
        sb.AppendLine($"    public static bool operator >({name} left, {name} right) => left.CompareTo(right) > 0;");
        sb.AppendLine($"    public static bool operator >=({name} left, {name} right) => left.CompareTo(right) >= 0;");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
