using System.Text;
using Moongazing.OrionKey.Generators.Model;
using ValueType = Moongazing.OrionKey.Generators.Model.ValueType;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits the core partial struct body: Value, ctor, Empty, New(), equality.</summary>
internal static class CoreBodyEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;
        var value = model.ValueKeyword;
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // v0.5.18: emit DebuggerDisplay so debuggers show "UserId: <value>" instead of
        // the default "{Demo.UserId}" which forces a struct expansion. Skip when the
        // consumer's partial declaration already carries [DebuggerDisplay] because the
        // attribute is not AllowMultiple = true and duplicating it would fail to
        // compile.
        if (!model.ConsumerHasDebuggerDisplay)
        {
            sb.AppendLine($"[global::System.Diagnostics.DebuggerDisplay(\"{name}: {{Value}}\")]");
        }
        sb.AppendLine($"readonly partial struct {name} : global::System.IEquatable<{name}>, global::System.IFormattable, global::System.ISpanFormattable");
        sb.AppendLine("{");
        sb.AppendLine($"    public {value} Value {{ get; }}");
        sb.AppendLine($"    public {name}({value} value) => Value = value;");

        var emptyArg = model.ValueType == ValueType.String ? "string.Empty" : "default";
        sb.AppendLine($"    public static readonly {name} Empty = new({emptyArg});");
        // v0.5.20: IsEmpty property for nullable-equivalence checks. Operators write
        // `if (userId.IsEmpty) ...` instead of `if (userId == UserId.Empty)`.
        // String-backed ids treat null Value as Empty (matches `Empty` ctor which uses
        // string.Empty); primitive-backed ids compare with default(T).
        if (model.ValueType == ValueType.String)
        {
            sb.AppendLine("    public bool IsEmpty => string.IsNullOrEmpty(Value);");
        }
        else
        {
            sb.AppendLine($"    public bool IsEmpty => Value.Equals(default({value}));");
        }

        if (model.GeneratesNew)
        {
            sb.AppendLine($"    public static {name} New() => new({NewExpression(model)});");
            // v0.5.22: CreateMany helper for seed data and tests. Real ergonomic when
            // a builder needs N fresh ids without a loop allocation at the call site:
            // `var users = UserId.CreateMany(50);` reads better than `Enumerable.Range
            // (0, 50).Select(_ => UserId.New()).ToArray()` and pre-allocates the array.
            sb.AppendLine($"    public static {name}[] CreateMany(int count)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (count < 0) throw new global::System.ArgumentOutOfRangeException(nameof(count));");
            sb.AppendLine($"        var arr = new {name}[count];");
            sb.AppendLine("        for (int i = 0; i < count; i++) arr[i] = New();");
            sb.AppendLine("        return arr;");
            sb.AppendLine("    }");
        }
        // v0.5.24: bulk wrap helper for converting collections of raw values to id
        // collections without LINQ boilerplate at every call site. Emitted for ALL
        // value types (Guid/int/long/string) because it works the same way - the
        // constructor accepts the underlying value.
        sb.AppendLine($"    public static global::System.Collections.Generic.IReadOnlyList<{name}> WrapAll(global::System.Collections.Generic.IEnumerable<{value}> values)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(values);");
        sb.AppendLine($"        var list = values is global::System.Collections.Generic.ICollection<{value}> c");
        sb.AppendLine($"            ? new global::System.Collections.Generic.List<{name}>(c.Count)");
        sb.AppendLine($"            : new global::System.Collections.Generic.List<{name}>();");
        sb.AppendLine("        foreach (var v in values) list.Add(new(v));");
        sb.AppendLine("        return list;");
        sb.AppendLine("    }");
        // v0.5.25: inverse of WrapAll - bulk unwrap for handing raw values to EF Core
        // Contains() queries, Dapper IN clauses, or external APIs that take the
        // underlying type. Same ICollection capacity optimization as WrapAll.
        sb.AppendLine($"    public static global::System.Collections.Generic.IReadOnlyList<{value}> UnwrapAll(global::System.Collections.Generic.IEnumerable<{name}> ids)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(ids);");
        sb.AppendLine($"        var list = ids is global::System.Collections.Generic.ICollection<{name}> c");
        sb.AppendLine($"            ? new global::System.Collections.Generic.List<{value}>(c.Count)");
        sb.AppendLine($"            : new global::System.Collections.Generic.List<{value}>();");
        sb.AppendLine("        foreach (var id in ids) list.Add(id.Value);");
        sb.AppendLine("        return list;");
        sb.AppendLine("    }");

        sb.AppendLine($"    public bool Equals({name} other) => Value.Equals(other.Value);");
        sb.AppendLine($"    public override bool Equals(object? obj) => obj is {name} other && Equals(other);");
        sb.AppendLine("    public override int GetHashCode() => Value.GetHashCode();");

        var toStr = model.ValueType == ValueType.String ? "Value" : "Value.ToString()";
        sb.AppendLine($"    public override string ToString() => {toStr};");

        // v0.5.11: IFormattable + ISpanFormattable so OrionId structs participate in
        // format-aware interpolations (e.g. $"{userId:N}" on a Guid-backed id forwards
        // to Guid's N format). String-backed ids ignore the format specifier - the
        // underlying string has no format semantics.
        if (model.ValueType == ValueType.String)
        {
            sb.AppendLine($"    public string ToString(string? format, global::System.IFormatProvider? formatProvider) => Value ?? string.Empty;");
            sb.AppendLine($"    public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)");
            sb.AppendLine("    {");
            sb.AppendLine("        var source = Value ?? string.Empty;");
            sb.AppendLine("        if (source.Length > destination.Length) { charsWritten = 0; return false; }");
            sb.AppendLine("        source.AsSpan().CopyTo(destination);");
            sb.AppendLine("        charsWritten = source.Length;");
            sb.AppendLine("        return true;");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    public string ToString(string? format, global::System.IFormatProvider? formatProvider) => Value.ToString(format, formatProvider);");
            sb.AppendLine($"    public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return ((global::System.ISpanFormattable)Value).TryFormat(destination, out charsWritten, format, provider);");
            sb.AppendLine("    }");
        }

        sb.AppendLine($"    public static bool operator ==({name} left, {name} right) => left.Equals(right);");
        sb.AppendLine($"    public static bool operator !=({name} left, {name} right) => !left.Equals(right);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string NewExpression(OrionIdModel model) => model.Strategy switch
    {
        StrategyType.Snowflake => "global::Moongazing.OrionKey.OrionKey.NextSnowflake()",
        StrategyType.Ulid => "global::Moongazing.OrionKey.OrionKey.NewUlid()",
        StrategyType.NanoId => "global::Moongazing.OrionKey.OrionKey.NewNanoId()",
        StrategyType.GuidV7 => "global::Moongazing.OrionKey.OrionKey.NewGuidV7()",
        StrategyType.Cuid2 => "global::Moongazing.OrionKey.OrionKey.NewCuid2()",
        StrategyType.Ksuid => "global::Moongazing.OrionKey.OrionKey.NewKsuid()",
        StrategyType.ObjectId => "global::Moongazing.OrionKey.OrionKey.NewObjectId()",
        StrategyType.SequentialGuid => "global::Moongazing.OrionKey.OrionKey.NewSequentialGuid()",
        StrategyType.MonotonicHex => "global::Moongazing.OrionKey.OrionKey.NewMonotonicHex()",
        StrategyType.None when model.ValueType == ValueType.Guid => "global::System.Guid.NewGuid()",
        _ => throw new System.InvalidOperationException("New() requested for a non-generating model."),
    };
}
