using System.Text;
using Moongazing.OrionKey.Generators.Model;
using ValueType = Moongazing.OrionKey.Generators.Model.ValueType;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits the core partial struct body: Value, ctor, Empty, New(), equality.</summary>
internal static class CoreBodyEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;
        var value = model.ValueKeyword;
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        // v0.5.18: emit DebuggerDisplay so debuggers show "UserId: <value>" instead of
        // the default "{Demo.UserId}" which forces a struct expansion. The format uses
        // the same toStr expression we use for ToString so string-backed and
        // primitive-backed ids both render naturally.
        var debuggerExpression = model.ValueType == ValueType.String ? "Value" : "Value";
        sb.AppendLine($"[global::System.Diagnostics.DebuggerDisplay(\"{name}: {{{debuggerExpression}}}\")]");
        sb.AppendLine($"readonly partial struct {name} : global::System.IEquatable<{name}>, global::System.IFormattable, global::System.ISpanFormattable");
        sb.AppendLine("{");
        sb.AppendLine($"    public {value} Value {{ get; }}");
        sb.AppendLine($"    public {name}({value} value) => Value = value;");

        var emptyArg = model.ValueType == ValueType.String ? "string.Empty" : "default";
        sb.AppendLine($"    public static readonly {name} Empty = new({emptyArg});");

        if (model.GeneratesNew)
        {
            sb.AppendLine($"    public static {name} New() => new({NewExpression(model)});");
        }

        sb.AppendLine($"    public bool Equals({name} other) => Value.Equals(other.Value);");
        sb.AppendLine($"    public override bool Equals(object? obj) => obj is {name} other && Equals(other);");
        sb.AppendLine("    public override int GetHashCode() => Value.GetHashCode();");

        var toStr = model.ValueType == ValueType.String ? "Value" : "Value.ToString()";
        sb.AppendLine($"    public override string ToString() => {toStr};");

        // v0.5.11: IFormattable + ISpanFormattable so OrionId structs participate in
        // format-aware interpolations (e.g. $"{userId:N}" on a Guid-backed id forwards
        // to Guid's N format). String-backed ids ignore the format specifier - the
        // underlying string has no format semantics.
        if (model.ValueType == ValueType.String)
        {
            sb.AppendLine($"    public string ToString(string? format, global::System.IFormatProvider? formatProvider) => Value ?? string.Empty;");
            sb.AppendLine($"    public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)");
            sb.AppendLine("    {");
            sb.AppendLine("        var source = Value ?? string.Empty;");
            sb.AppendLine("        if (source.Length > destination.Length) { charsWritten = 0; return false; }");
            sb.AppendLine("        source.AsSpan().CopyTo(destination);");
            sb.AppendLine("        charsWritten = source.Length;");
            sb.AppendLine("        return true;");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    public string ToString(string? format, global::System.IFormatProvider? formatProvider) => Value.ToString(format, formatProvider);");
            sb.AppendLine($"    public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return ((global::System.ISpanFormattable)Value).TryFormat(destination, out charsWritten, format, provider);");
            sb.AppendLine("    }");
        }

        sb.AppendLine($"    public static bool operator ==({name} left, {name} right) => left.Equals(right);");
        sb.AppendLine($"    public static bool operator !=({name} left, {name} right) => !left.Equals(right);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string NewExpression(OrionIdModel model) => model.Strategy switch
    {
        StrategyType.Snowflake => "global::Moongazing.OrionKey.OrionKey.NextSnowflake()",
        StrategyType.Ulid => "global::Moongazing.OrionKey.OrionKey.NewUlid()",
        StrategyType.NanoId => "global::Moongazing.OrionKey.OrionKey.NewNanoId()",
        StrategyType.GuidV7 => "global::Moongazing.OrionKey.OrionKey.NewGuidV7()",
        StrategyType.Cuid2 => "global::Moongazing.OrionKey.OrionKey.NewCuid2()",
        StrategyType.Ksuid => "global::Moongazing.OrionKey.OrionKey.NewKsuid()",
        StrategyType.ObjectId => "global::Moongazing.OrionKey.OrionKey.NewObjectId()",
        StrategyType.SequentialGuid => "global::Moongazing.OrionKey.OrionKey.NewSequentialGuid()",
        StrategyType.None when model.ValueType == ValueType.Guid => "global::System.Guid.NewGuid()",
        _ => throw new System.InvalidOperationException("New() requested for a non-generating model."),
    };
}
