using System.Text;
using Moongazing.OrionKey.Generators.Model;
using ValueType = Moongazing.OrionKey.Generators.Model.ValueType;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits the core partial struct body: Value, ctor, Empty, New(), equality.</summary>
internal static class CoreBodyEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;
        var value = model.ValueKeyword;
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"readonly partial struct {name} : global::System.IEquatable<{name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {value} Value {{ get; }}");
        sb.AppendLine($"    public {name}({value} value) => Value = value;");

        var emptyArg = model.ValueType == ValueType.String ? "string.Empty" : "default";
        sb.AppendLine($"    public static readonly {name} Empty = new({emptyArg});");

        if (model.GeneratesNew)
        {
            sb.AppendLine($"    public static {name} New() => new({NewExpression(model)});");
        }

        sb.AppendLine($"    public bool Equals({name} other) => Value.Equals(other.Value);");
        sb.AppendLine($"    public override bool Equals(object? obj) => obj is {name} other && Equals(other);");
        sb.AppendLine("    public override int GetHashCode() => Value.GetHashCode();");

        var toStr = model.ValueType == ValueType.String ? "Value" : "Value.ToString()";
        sb.AppendLine($"    public override string ToString() => {toStr};");

        sb.AppendLine($"    public static bool operator ==({name} left, {name} right) => left.Equals(right);");
        sb.AppendLine($"    public static bool operator !=({name} left, {name} right) => !left.Equals(right);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string NewExpression(OrionIdModel model) => model.Strategy switch
    {
        StrategyType.Snowflake => "global::Moongazing.OrionKey.OrionKey.NextSnowflake()",
        StrategyType.Ulid => "global::Moongazing.OrionKey.OrionKey.NewUlid()",
        StrategyType.NanoId => "global::Moongazing.OrionKey.OrionKey.NewNanoId()",
        StrategyType.GuidV7 => "global::Moongazing.OrionKey.OrionKey.NewGuidV7()",
        StrategyType.None when model.ValueType == ValueType.Guid => "global::System.Guid.NewGuid()",
        _ => throw new System.InvalidOperationException("New() requested for a non-generating model."),
    };
}
