using System.Text;
using Moongazing.OrionKey.Generators.Model;
using ValueType = Moongazing.OrionKey.Generators.Model.ValueType;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits a Dapper SqlMapper.TypeHandler. Only invoked when Dapper is referenced.</summary>
internal static class DapperTypeHandlerEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;
        var handler = $"{name}DapperTypeHandler";

        var dbType = model.ValueType switch
        {
            ValueType.Guid => "global::System.Data.DbType.Guid",
            ValueType.Int32 => "global::System.Data.DbType.Int32",
            ValueType.Int64 => "global::System.Data.DbType.Int64",
            ValueType.String => "global::System.Data.DbType.String",
            _ => throw new System.ArgumentOutOfRangeException(nameof(model)),
        };

        var parseExpr = model.ValueType switch
        {
            ValueType.Guid =>
                $"value is global::System.Guid g ? new {name}(g) "
                + $": new {name}(global::System.Guid.Parse((string)value!))",
            ValueType.Int32 =>
                $"new {name}(global::System.Convert.ToInt32(value, "
                + "global::System.Globalization.CultureInfo.InvariantCulture))",
            ValueType.Int64 =>
                $"new {name}(global::System.Convert.ToInt64(value, "
                + "global::System.Globalization.CultureInfo.InvariantCulture))",
            ValueType.String => $"new {name}((string)value!)",
            _ => throw new System.ArgumentOutOfRangeException(nameof(model)),
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }
        sb.AppendLine($"/// <summary>Dapper type handler for <see cref=\"{name}\"/>.</summary>");
        sb.AppendLine($"public sealed class {handler} "
                    + $": global::Dapper.SqlMapper.TypeHandler<{name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public override {name} Parse(object value) => {parseExpr};");
        sb.AppendLine($"    public override void SetValue("
                    + $"global::System.Data.IDbDataParameter parameter, {name} value)");
        sb.AppendLine("    {");
        sb.AppendLine($"        parameter.DbType = {dbType};");
        sb.AppendLine("        parameter.Value = value.Value;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
