using System.Text;
using Moongazing.OrionKey.Generators.Model;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits an EF Core ValueConverter. Only invoked when EF Core is referenced.</summary>
internal static class EfCoreConverterEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;
        var value = model.ValueKeyword;
        var converter = $"{name}ValueConverter";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>EF Core value converter for <see cref=\"{name}\"/>.</summary>");
        sb.AppendLine($"public sealed class {converter} : "
                    + "global::Microsoft.EntityFrameworkCore.Storage.ValueConversion."
                    + $"ValueConverter<{name}, {value}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {converter}() : base(id => id.Value, value => new {name}(value)) {{ }}");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
