using System.Text;
using Moongazing.OrionKey.Generators.Model;
using ValueType = Moongazing.OrionKey.Generators.Model.ValueType;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits a System.Text.Json converter and attaches it to the id struct.</summary>
internal static class JsonConverterEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;
        var converter = $"{name}JsonConverter";

        var (readExpr, writeStmt) = model.ValueType switch
        {
            ValueType.Guid => ("reader.GetGuid()", "writer.WriteStringValue(value.Value)"),
            ValueType.Int32 => ("reader.GetInt32()", "writer.WriteNumberValue(value.Value)"),
            ValueType.Int64 => ("reader.GetInt64()", "writer.WriteNumberValue(value.Value)"),
            ValueType.String => ("reader.GetString()!", "writer.WriteStringValue(value.Value)"),
            _ => throw new System.ArgumentOutOfRangeException(nameof(model)),
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"[global::System.Text.Json.Serialization.JsonConverter(typeof({converter}))]");
        sb.AppendLine($"readonly partial struct {name} {{ }}");
        sb.AppendLine();
        sb.AppendLine($"internal sealed class {converter} "
                    + $": global::System.Text.Json.Serialization.JsonConverter<{name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public override {name} Read("
                    + "ref global::System.Text.Json.Utf8JsonReader reader, "
                    + "global::System.Type typeToConvert, "
                    + "global::System.Text.Json.JsonSerializerOptions options) "
                    + $"=> new({readExpr});");
        sb.AppendLine($"    public override void Write("
                    + "global::System.Text.Json.Utf8JsonWriter writer, "
                    + $"{name} value, "
                    + "global::System.Text.Json.JsonSerializerOptions options) "
                    + $"=> {writeStmt};");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
