using System.Text;
using Moongazing.OrionKey.Generators.Model;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits a MongoDB BSON serializer. Only invoked when MongoDB.Driver is referenced.</summary>
internal static class MongoBsonSerializerEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;
        var value = model.ValueKeyword;
        var serializer = $"{name}BsonSerializer";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }
        sb.AppendLine($"/// <summary>MongoDB BSON serializer for <see cref=\"{name}\"/>.</summary>");
        sb.AppendLine($"public sealed class {serializer} "
                    + $": global::MongoDB.Bson.Serialization.Serializers.SerializerBase<{name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    private static readonly global::MongoDB.Bson.Serialization.IBsonSerializer<{value}> "
                    + $"PrimitiveSerializer = global::MongoDB.Bson.Serialization.BsonSerializer.LookupSerializer<{value}>();");
        sb.AppendLine();
        sb.AppendLine($"    public override {name} Deserialize("
                    + "global::MongoDB.Bson.Serialization.BsonDeserializationContext context, "
                    + "global::MongoDB.Bson.Serialization.BsonDeserializationArgs args)");
        sb.AppendLine($"        => new(PrimitiveSerializer.Deserialize(context, args));");
        sb.AppendLine();
        sb.AppendLine($"    public override void Serialize("
                    + "global::MongoDB.Bson.Serialization.BsonSerializationContext context, "
                    + "global::MongoDB.Bson.Serialization.BsonSerializationArgs args, "
                    + $"{name} value)");
        sb.AppendLine("        => PrimitiveSerializer.Serialize(context, args, value.Value);");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
