using System.Text;
using Moongazing.OrionKey.Generators.Model;
using ValueType = Moongazing.OrionKey.Generators.Model.ValueType;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits a Newtonsoft.Json JsonConverter. Only invoked when Newtonsoft.Json is referenced.</summary>
internal static class NewtonsoftJsonConverterEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;
        var converter = $"{name}NewtonsoftJsonConverter";

        var readExpr = model.ValueType switch
        {
            ValueType.Guid =>
                "reader.Value is global::System.Guid g ? g "
                + ": global::System.Guid.Parse(reader.Value!.ToString()!)",
            ValueType.Int32 =>
                "global::System.Convert.ToInt32(reader.Value, "
                + "global::System.Globalization.CultureInfo.InvariantCulture)",
            ValueType.Int64 =>
                "global::System.Convert.ToInt64(reader.Value, "
                + "global::System.Globalization.CultureInfo.InvariantCulture)",
            ValueType.String => "(string)reader.Value!",
            _ => throw new System.ArgumentOutOfRangeException(nameof(model)),
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }
        // v0.5.19: emit [JsonConverter] on a separate partial declaration of the
        // struct so Newtonsoft.Json picks the converter up automatically without the
        // consumer having to call settings.Converters.Add(...). Matches the
        // System.Text.Json side's pattern.
        sb.AppendLine($"[global::Newtonsoft.Json.JsonConverter(typeof({converter}))]");
        sb.AppendLine($"readonly partial struct {name} {{ }}");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Newtonsoft.Json converter for <see cref=\"{name}\"/>.</summary>");
        sb.AppendLine($"public sealed class {converter} "
                    + $": global::Newtonsoft.Json.JsonConverter<{name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public override {name} ReadJson("
                    + "global::Newtonsoft.Json.JsonReader reader, "
                    + "global::System.Type objectType, "
                    + $"{name} existingValue, bool hasExistingValue, "
                    + "global::Newtonsoft.Json.JsonSerializer serializer)");
        sb.AppendLine($"        => new({readExpr});");
        sb.AppendLine($"    public override void WriteJson("
                    + "global::Newtonsoft.Json.JsonWriter writer, "
                    + $"{name} value, global::Newtonsoft.Json.JsonSerializer serializer)");
        sb.AppendLine("        => writer.WriteValue(value.Value);");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
