using System.Text;
using Moongazing.OrionKey.Generators.Model;
using ValueType = Moongazing.OrionKey.Generators.Model.ValueType;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits a Swashbuckle ISchemaFilter. Only invoked when Swashbuckle.AspNetCore is referenced.</summary>
internal static class OpenApiSchemaFilterEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;
        var filter = $"{name}SchemaFilter";

        var (schemaType, schemaFormat) = model.ValueType switch
        {
            ValueType.Guid => ("string", "uuid"),
            ValueType.Int32 => ("integer", "int32"),
            ValueType.Int64 => ("integer", "int64"),
            ValueType.String => ("string", null),
            _ => throw new System.ArgumentOutOfRangeException(nameof(model)),
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }
        sb.AppendLine($"/// <summary>Swashbuckle schema filter that maps <see cref=\"{name}\"/> to its underlying primitive in OpenAPI.</summary>");
        sb.AppendLine($"public sealed class {filter} "
                    + ": global::Swashbuckle.AspNetCore.SwaggerGen.ISchemaFilter");
        sb.AppendLine("{");
        sb.AppendLine($"    public void Apply("
                    + "global::Microsoft.OpenApi.Models.OpenApiSchema schema, "
                    + "global::Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext context)");
        sb.AppendLine("    {");
        sb.AppendLine($"        if (context.Type != typeof({name})) return;");
        sb.AppendLine($"        schema.Type = \"{schemaType}\";");
        sb.AppendLine(schemaFormat is null
            ? "        schema.Format = null;"
            : $"        schema.Format = \"{schemaFormat}\";");
        sb.AppendLine("        schema.Properties?.Clear();");
        sb.AppendLine("        schema.Required?.Clear();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
