using System.Text;
using Moongazing.OrionKey.Generators.Model;
using ValueType = Moongazing.OrionKey.Generators.Model.ValueType;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits explicit IParsable/ISpanParsable members for minimal-API binding.</summary>
internal static class ParsableEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;

        var (parseStr, tryBody) = model.ValueType switch
        {
            ValueType.Guid => (
                "new(global::System.Guid.Parse(s))",
                "if (global::System.Guid.TryParse(s, provider, out var v)) { result = new(v); return true; } result = default; return false;"),
            ValueType.Int32 => (
                "new(int.Parse(s, provider))",
                "if (int.TryParse(s, provider, out var v)) { result = new(v); return true; } result = default; return false;"),
            ValueType.Int64 => (
                "new(long.Parse(s, provider))",
                "if (long.TryParse(s, provider, out var v)) { result = new(v); return true; } result = default; return false;"),
            ValueType.String => (
                "new(s.ToString())",
                "if (s is null) { result = default; return false; } result = new(s.ToString()); return true;"),
            _ => throw new System.ArgumentOutOfRangeException(nameof(model)),
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"readonly partial struct {name} : "
                    + $"global::System.IParsable<{name}>, global::System.ISpanParsable<{name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    static {name} global::System.IParsable<{name}>.Parse("
                    + "string s, global::System.IFormatProvider? provider) "
                    + $"=> {parseStr};");
        sb.AppendLine($"    static bool global::System.IParsable<{name}>.TryParse("
                    + "string? s, global::System.IFormatProvider? provider, "
                    + $"out {name} result) {{ {tryBody} }}");
        sb.AppendLine($"    static {name} global::System.ISpanParsable<{name}>.Parse("
                    + "global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider) "
                    + $"=> {ParseSpan(model)};");
        sb.AppendLine($"    static bool global::System.ISpanParsable<{name}>.TryParse("
                    + "global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, "
                    + $"out {name} result) {{ {TrySpanBody(model)} }}");
        // Public TryParse overloads so ASP.NET Core minimal-API route binding can
        // discover them: ParameterBindingMethodCache only accepts public static
        // TryParse methods declared on the type, not explicit interface members.
        sb.AppendLine($"    public static bool TryParse("
                    + "string? s, global::System.IFormatProvider? provider, "
                    + $"out {name} result) {{ {tryBody} }}");
        sb.AppendLine($"    public static bool TryParse("
                    + $"string? s, out {name} result) => TryParse(s, null, out result);");
        // v0.5.21: ParseOrDefault helper. Returns null on null/empty/malformed input
        // instead of throwing. Useful when the caller is parsing user-supplied / query-
        // string input and would otherwise wrap every Parse call in try/catch.
        //
        // ONLY emitted for primitive-backed types (Guid/int/long) because the
        // generated string-backed TryParse accepts ANY non-null string - returning a
        // 'parsed' StringId for arbitrary input like 'not-a-ulid' would defeat the
        // 'null-on-malformed' contract. String-backed consumers should parse via
        // their strategy's own validator before calling ctor / Parse.
        if (model.ValueType != ValueType.String)
        {
            sb.AppendLine($"    public static {name}? ParseOrDefault(string? s)");
            sb.AppendLine("    {");
            sb.AppendLine($"        if (string.IsNullOrEmpty(s)) return null;");
            sb.AppendLine($"        return TryParse(s, null, out var r) ? r : null;");
            sb.AppendLine("    }");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string ParseSpan(OrionIdModel model) => model.ValueType switch
    {
        ValueType.Guid => "new(global::System.Guid.Parse(s))",
        ValueType.Int32 => "new(int.Parse(s, provider))",
        ValueType.Int64 => "new(long.Parse(s, provider))",
        ValueType.String => "new(s.ToString())",
        _ => throw new System.ArgumentOutOfRangeException(nameof(model)),
    };

    private static string TrySpanBody(OrionIdModel model) => model.ValueType switch
    {
        ValueType.Guid =>
            "if (global::System.Guid.TryParse(s, provider, out var v)) { result = new(v); return true; } result = default; return false;",
        ValueType.Int32 =>
            "if (int.TryParse(s, provider, out var v)) { result = new(v); return true; } result = default; return false;",
        ValueType.Int64 =>
            "if (long.TryParse(s, provider, out var v)) { result = new(v); return true; } result = default; return false;",
        ValueType.String =>
            "result = new(s.ToString()); return true;",
        _ => throw new System.ArgumentOutOfRangeException(nameof(model)),
    };
}
