using System.Collections.Generic;
using System.Text;
using Moongazing.OrionKey.Generators.Model;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>
/// Emits per-library aggregate registrar classes that enumerate every generated companion
/// in the consumer assembly. One method body per registrar, one statement per id.
/// </summary>
internal static class RegistrationEmitter
{
    public static string EmitDapper(IReadOnlyList<OrionIdModel> models)
        => EmitRegistrar(
            className: "OrionKeyDapperRegistrar",
            summary: "Registers every generated Dapper type handler with the Dapper SqlMapper.",
            signature: "Register()",
            body: BuildStatements(models, m =>
                $"global::Dapper.SqlMapper.AddTypeHandler(new {Qualify(m)}DapperTypeHandler());"));

    public static string EmitNewtonsoftJson(IReadOnlyList<OrionIdModel> models)
        => EmitRegistrar(
            className: "OrionKeyNewtonsoftJsonRegistrar",
            summary: "Adds every generated Newtonsoft.Json converter to the supplied settings.",
            signature: "AddTo(global::Newtonsoft.Json.JsonSerializerSettings settings)",
            body: BuildStatements(models, m =>
                $"settings.Converters.Add(new {Qualify(m)}NewtonsoftJsonConverter());"));

    public static string EmitMongo(IReadOnlyList<OrionIdModel> models)
        => EmitRegistrar(
            className: "OrionKeyMongoRegistrar",
            summary: "Registers every generated MongoDB BSON serializer with BsonSerializer.",
            signature: "Register()",
            body: BuildStatements(models, m =>
                "global::MongoDB.Bson.Serialization.BsonSerializer.RegisterSerializer("
                + $"typeof({Qualify(m)}), new {Qualify(m)}BsonSerializer());"));

    public static string EmitOpenApi(IReadOnlyList<OrionIdModel> models)
        => EmitRegistrar(
            className: "OrionKeyOpenApiRegistrar",
            summary: "Adds every generated Swashbuckle schema filter to the supplied options.",
            signature: "AddTo(global::Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions options)",
            body: BuildStatements(models, m =>
                $"global::Microsoft.Extensions.DependencyInjection.SwaggerGenOptionsExtensions.SchemaFilter<{Qualify(m)}SchemaFilter>(options);"));

    /// <summary>
    /// Emits the System.Text.Json source-generation-friendly aggregate: a reflection-free
    /// <c>JsonConverterFactory</c> that maps each generated id type to its
    /// <c>JsonConverter&lt;T&gt;</c> via a static <c>typeToConvert</c> switch (no
    /// <c>MakeGenericType</c> / reflection), plus an <c>AddTo(JsonSerializerOptions)</c>
    /// registrar so every id converter can be wired into a <c>JsonSerializerContext</c>'s
    /// options in a single call instead of one <c>Converters.Add</c> per id. Both are
    /// trimming/NativeAOT-safe because the converter set is closed and known at compile time.
    /// </summary>
    public static string EmitSystemTextJson(IReadOnlyList<OrionIdModel> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Reflection-free factory: a closed type switch over the generated id types.
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Reflection-free <see cref=\"global::System.Text.Json.Serialization.JsonConverterFactory\"/>");
        sb.AppendLine("/// covering every <c>[OrionId]</c> type in this assembly. AOT/trimming safe: the");
        sb.AppendLine("/// supported set is closed and resolved by a compile-time type switch.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public sealed class OrionKeyJsonConverterFactory "
                    + ": global::System.Text.Json.Serialization.JsonConverterFactory");
        sb.AppendLine("{");
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    public override bool CanConvert(global::System.Type typeToConvert)");
        sb.AppendLine("    {");
        foreach (var model in models)
        {
            sb.AppendLine($"        if (typeToConvert == typeof({Qualify(model)})) return true;");
        }
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine("    public override global::System.Text.Json.Serialization.JsonConverter? CreateConverter(");
        sb.AppendLine("        global::System.Type typeToConvert,");
        sb.AppendLine("        global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("    {");
        foreach (var model in models)
        {
            sb.AppendLine($"        if (typeToConvert == typeof({Qualify(model)})) return new {QualifyConverter(model)}();");
        }
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // One-call registrar for a JsonSerializerContext's options.
        sb.AppendLine("/// <summary>Adds every generated System.Text.Json converter to the supplied options.</summary>");
        sb.AppendLine("public static class OrionKeyJsonRegistrar");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers every generated id converter on <paramref name=\"options\"/>. Safe to use");
        sb.AppendLine("    /// alongside a <c>JsonSerializerContext</c> (source-generation mode): the explicit");
        sb.AppendLine("    /// converters take precedence over the context's metadata for the id types.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void AddTo(global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(options);");
        foreach (var model in models)
        {
            sb.AppendLine($"        options.Converters.Add(new {QualifyConverter(model)}());");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Qualify(OrionIdModel model)
        => model.Namespace.Length == 0
            ? $"global::{model.Name}"
            : $"global::{model.Namespace}.{model.Name}";

    private static string QualifyConverter(OrionIdModel model)
        => model.Namespace.Length == 0
            ? $"global::{model.Name}JsonConverter"
            : $"global::{model.Namespace}.{model.Name}JsonConverter";

    private static string BuildStatements(
        IReadOnlyList<OrionIdModel> models,
        System.Func<OrionIdModel, string> render)
    {
        var sb = new StringBuilder();
        foreach (var model in models)
        {
            sb.Append("        ");
            sb.AppendLine(render(model));
        }
        return sb.ToString();
    }

    private static string EmitRegistrar(string className, string summary, string signature, string body)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>{summary}</summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static void {signature}");
        sb.AppendLine("    {");
        sb.Append(body);
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
