using System.Collections.Generic;
using System.Text;
using Moongazing.OrionKey.Generators.Model;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>
/// Emits per-library aggregate registrar classes that enumerate every generated companion
/// in the consumer assembly. One method body per registrar, one statement per id.
/// </summary>
internal static class RegistrationEmitter
{
    public static string EmitDapper(IReadOnlyList<OrionIdModel> models)
        => EmitRegistrar(
            className: "OrionKeyDapperRegistrar",
            summary: "Registers every generated Dapper type handler with the Dapper SqlMapper.",
            signature: "Register()",
            body: BuildStatements(models, m =>
                $"global::Dapper.SqlMapper.AddTypeHandler(new {Qualify(m)}DapperTypeHandler());"));

    public static string EmitNewtonsoftJson(IReadOnlyList<OrionIdModel> models)
        => EmitRegistrar(
            className: "OrionKeyNewtonsoftJsonRegistrar",
            summary: "Adds every generated Newtonsoft.Json converter to the supplied settings.",
            signature: "AddTo(global::Newtonsoft.Json.JsonSerializerSettings settings)",
            body: BuildStatements(models, m =>
                $"settings.Converters.Add(new {Qualify(m)}NewtonsoftJsonConverter());"));

    public static string EmitMongo(IReadOnlyList<OrionIdModel> models)
        => EmitRegistrar(
            className: "OrionKeyMongoRegistrar",
            summary: "Registers every generated MongoDB BSON serializer with BsonSerializer.",
            signature: "Register()",
            body: BuildStatements(models, m =>
                "global::MongoDB.Bson.Serialization.BsonSerializer.RegisterSerializer("
                + $"typeof({Qualify(m)}), new {Qualify(m)}BsonSerializer());"));

    public static string EmitOpenApi(IReadOnlyList<OrionIdModel> models)
        => EmitRegistrar(
            className: "OrionKeyOpenApiRegistrar",
            summary: "Adds every generated Swashbuckle schema filter to the supplied options.",
            signature: "AddTo(global::Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions options)",
            body: BuildStatements(models, m =>
                $"global::Microsoft.Extensions.DependencyInjection.SwaggerGenOptionsExtensions.SchemaFilter<{Qualify(m)}SchemaFilter>(options);"));

    private static string Qualify(OrionIdModel model)
        => model.Namespace.Length == 0
            ? $"global::{model.Name}"
            : $"global::{model.Namespace}.{model.Name}";

    private static string BuildStatements(
        IReadOnlyList<OrionIdModel> models,
        System.Func<OrionIdModel, string> render)
    {
        var sb = new StringBuilder();
        foreach (var model in models)
        {
            sb.Append("        ");
            sb.AppendLine(render(model));
        }
        return sb.ToString();
    }

    private static string EmitRegistrar(string className, string summary, string signature, string body)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>{summary}</summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static void {signature}");
        sb.AppendLine("    {");
        sb.Append(body);
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
