using System.Text;
using Moongazing.OrionKey.Generators.Model;
using ValueType = Moongazing.OrionKey.Generators.Model.ValueType;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>Emits a TypeConverter for ASP.NET Core route/query/form binding.</summary>
internal static class TypeConverterEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;
        var converter = $"{name}TypeConverter";

        var parseExpr = model.ValueType switch
        {
            ValueType.Guid => "global::System.Guid.Parse(text)",
            ValueType.Int32 => "int.Parse(text, global::System.Globalization.CultureInfo.InvariantCulture)",
            ValueType.Int64 => "long.Parse(text, global::System.Globalization.CultureInfo.InvariantCulture)",
            ValueType.String => "text",
            _ => throw new System.ArgumentOutOfRangeException(nameof(model)),
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"[global::System.ComponentModel.TypeConverter(typeof({converter}))]");
        sb.AppendLine($"readonly partial struct {name} {{ }}");
        sb.AppendLine();
        sb.AppendLine($"file sealed class {converter} : global::System.ComponentModel.TypeConverter");
        sb.AppendLine("{");
        sb.AppendLine($"    [global::System.Diagnostics.CodeAnalysis.DynamicDependency("
                    + "(global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors), "
                    + $"typeof({converter}))]");
        sb.AppendLine($"    public {converter}() {{ }}");
        sb.AppendLine("    public override bool CanConvertFrom("
                    + "global::System.ComponentModel.ITypeDescriptorContext? context, "
                    + "global::System.Type sourceType) "
                    + "=> sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);");
        sb.AppendLine("    public override object? ConvertFrom("
                    + "global::System.ComponentModel.ITypeDescriptorContext? context, "
                    + "global::System.Globalization.CultureInfo? culture, object value) "
                    + $"=> value is string text ? new {name}({parseExpr}) "
                    + ": base.ConvertFrom(context, culture, value);");
        sb.AppendLine("    public override bool CanConvertTo("
                    + "global::System.ComponentModel.ITypeDescriptorContext? context, "
                    + "global::System.Type? destinationType) "
                    + "=> destinationType == typeof(string) || base.CanConvertTo(context, destinationType);");
        sb.AppendLine("    public override object? ConvertTo("
                    + "global::System.ComponentModel.ITypeDescriptorContext? context, "
                    + "global::System.Globalization.CultureInfo? culture, object? value, "
                    + "global::System.Type destinationType) "
                    + $"=> destinationType == typeof(string) && value is {name} id "
                    + "? id.ToString() : base.ConvertTo(context, culture, value, destinationType);");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
