using System.Text;
using Moongazing.OrionKey.Generators.Model;
using ValueType = Moongazing.OrionKey.Generators.Model.ValueType;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>
/// v0.5.27: emits <c>System.IUtf8SpanFormattable</c> - the UTF-8 counterpart to the
/// v0.5.11 ISpanFormattable surface. Lets an OrionId format itself directly into a
/// <c>Span&lt;byte&gt;</c> with no intermediate string/char-span allocation, which is the path
/// System.Text.Json's writer and <c>Utf8.TryWrite</c> interpolated handlers take. Guarded by
/// <c>#if NET8_0_OR_GREATER</c> because the interface ships in net8: older consumers (the
/// existing ISpanParsable/IParsable surface already requires net7) simply do not see it.
/// </summary>
internal static class Utf8SpanFormattableEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;

        var body = model.ValueType switch
        {
            ValueType.Guid or ValueType.Int32 or ValueType.Int64 =>
                "        return ((global::System.IUtf8SpanFormattable)Value)"
                + ".TryFormat(utf8Destination, out bytesWritten, format, provider);",
            ValueType.String =>
                "        var source = Value ?? string.Empty;\n"
                + "        return global::System.Text.Encoding.UTF8"
                + ".TryGetBytes(source, utf8Destination, out bytesWritten);",
            _ => throw new System.ArgumentOutOfRangeException(nameof(model)),
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#if NET8_0_OR_GREATER");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"readonly partial struct {name} : global::System.IUtf8SpanFormattable");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Formats the id directly into a UTF-8 byte span (no string allocation).</summary>");
        sb.AppendLine("    public bool TryFormat(global::System.Span<byte> utf8Destination, out int bytesWritten, "
                    + "global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider)");
        sb.AppendLine("    {");
        sb.AppendLine(body);
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("#endif");
        return sb.ToString();
    }
}
