using System.Text;
using Moongazing.OrionKey.Generators.Model;
using ValueType = Moongazing.OrionKey.Generators.Model.ValueType;

namespace Moongazing.OrionKey.Generators.Emit;

/// <summary>
/// v0.5.28: emits <c>System.IUtf8SpanParsable</c> - the UTF-8 parse counterpart to the v0.5.27
/// IUtf8SpanFormattable surface, completing the allocation-free UTF-8 round-trip. Lets an OrionId
/// be parsed directly from a <c>ReadOnlySpan&lt;byte&gt;</c> (e.g. a Utf8JsonReader value span) with
/// no intermediate string. Numeric backings call the concrete UTF-8 parse overload directly (never
/// a boxing interface dispatch); string backings decode the UTF-8 bytes. Guarded by
/// <c>#if NET8_0_OR_GREATER</c> because the interface ships in net8.
/// </summary>
internal static class Utf8SpanParsableEmitter
{
    public static string Emit(OrionIdModel model)
    {
        var name = model.Name;

        // The single per-type TryParse body. Numeric/Guid branches call the concrete UTF-8 parse
        // overload directly (no boxing); the string branch rejects malformed UTF-8 with the
        // net8 Utf8.IsValid check FIRST - Encoding.UTF8.GetString uses replacement fallback and
        // would otherwise silently turn invalid bytes into a corrupted id (codex P2), unlike the
        // strict numeric/Guid branches. Guid's UTF-8 overload takes no IFormatProvider.
        var tryBody = model.ValueType switch
        {
            ValueType.Guid =>
                "if (global::System.Guid.TryParse(utf8, out var v)) { result = new(v); return true; } result = default; return false;",
            ValueType.Int32 =>
                "if (int.TryParse(utf8, provider, out var v)) { result = new(v); return true; } result = default; return false;",
            ValueType.Int64 =>
                "if (long.TryParse(utf8, provider, out var v)) { result = new(v); return true; } result = default; return false;",
            ValueType.String =>
                "if (!global::System.Text.Unicode.Utf8.IsValid(utf8)) { result = default; return false; } "
                + "result = new(global::System.Text.Encoding.UTF8.GetString(utf8)); return true;",
            _ => throw new System.ArgumentOutOfRangeException(nameof(model)),
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#if NET8_0_OR_GREATER");
        if (model.Namespace.Length != 0)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"readonly partial struct {name} : global::System.IUtf8SpanParsable<{name}>");
        sb.AppendLine("{");
        // Public overloads (the single validation point) so consumer code can parse from a UTF-8
        // buffer without the generic dispatch, mirroring the v0.5.23 public ReadOnlySpan<char>
        // overloads.
        sb.AppendLine($"    /// <summary>Parses the id from a UTF-8 byte span (no string allocation on numeric backings; rejects malformed input).</summary>");
        sb.AppendLine($"    public static bool TryParse("
                    + "global::System.ReadOnlySpan<byte> utf8, global::System.IFormatProvider? provider, "
                    + $"out {name} result) {{ {tryBody} }}");
        sb.AppendLine($"    public static bool TryParse("
                    + $"global::System.ReadOnlySpan<byte> utf8, out {name} result) => TryParse(utf8, null, out result);");
        // Explicit interface members delegate to the public overload so the validation logic lives
        // in exactly one place and the id flows through generic UTF-8 parsing constraints.
        sb.AppendLine($"    static {name} global::System.IUtf8SpanParsable<{name}>.Parse("
                    + "global::System.ReadOnlySpan<byte> utf8, global::System.IFormatProvider? provider) "
                    + $"=> TryParse(utf8, provider, out var r) ? r "
                    + $": throw new global::System.FormatException(\"Cannot parse the UTF-8 input as {name}.\");");
        sb.AppendLine($"    static bool global::System.IUtf8SpanParsable<{name}>.TryParse("
                    + "global::System.ReadOnlySpan<byte> utf8, global::System.IFormatProvider? provider, "
                    + $"out {name} result) => TryParse(utf8, provider, out result);");
        sb.AppendLine("}");
        sb.AppendLine("#endif");
        return sb.ToString();
    }
}
